# Generated by Django 5.2.7 on 2025-10-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=250)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.topic')),
            ],
        ),
    ]
