# Generated by Django 5.2.7 on 2025-10-21 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_topic_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.customer'),
            preserve_default=False,
        ),
    ]
